
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.endgamereborn.init;

import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.Registry;

import net.mcreator.endgamereborn.item.SteelSwordItem;
import net.mcreator.endgamereborn.item.SteelShovelItem;
import net.mcreator.endgamereborn.item.SteelPickaxeItem;
import net.mcreator.endgamereborn.item.SteelIngotItem;
import net.mcreator.endgamereborn.item.SteelHoeItem;
import net.mcreator.endgamereborn.item.SteelAxeItem;
import net.mcreator.endgamereborn.item.SteelArmorItem;
import net.mcreator.endgamereborn.item.SculkSteelSwordItem;
import net.mcreator.endgamereborn.item.SculkSteelShovelItem;
import net.mcreator.endgamereborn.item.SculkSteelPickaxeItem;
import net.mcreator.endgamereborn.item.SculkSteelIngotItem;
import net.mcreator.endgamereborn.item.SculkSteelHoeItem;
import net.mcreator.endgamereborn.item.SculkSteelAxeItem;
import net.mcreator.endgamereborn.item.SculkSteelArmorItem;
import net.mcreator.endgamereborn.item.RemnantSteelScrapItem;
import net.mcreator.endgamereborn.item.ReinforcedSteelSwordItem;
import net.mcreator.endgamereborn.item.ReinforcedSteelShovelItem;
import net.mcreator.endgamereborn.item.ReinforcedSteelPickaxeItem;
import net.mcreator.endgamereborn.item.ReinforcedSteelIngotItem;
import net.mcreator.endgamereborn.item.ReinforcedSteelHoeItem;
import net.mcreator.endgamereborn.item.ReinforcedSteelAxeItem;
import net.mcreator.endgamereborn.item.ReinforcedSteelArmorItem;
import net.mcreator.endgamereborn.item.ProsperousSteelSwordItem;
import net.mcreator.endgamereborn.item.ProsperousSteelShovelItem;
import net.mcreator.endgamereborn.item.ProsperousSteelPickaxeItem;
import net.mcreator.endgamereborn.item.ProsperousSteelIngotItem;
import net.mcreator.endgamereborn.item.ProsperousSteelHoeItem;
import net.mcreator.endgamereborn.item.ProsperousSteelAxeItem;
import net.mcreator.endgamereborn.item.ProsperousSteelArmorItem;
import net.mcreator.endgamereborn.item.NetheriteSwordItem;
import net.mcreator.endgamereborn.item.NetheriteShovelRebornItem;
import net.mcreator.endgamereborn.item.NetheritePickaxeRebornItem;
import net.mcreator.endgamereborn.item.NetheriteHoeRebornItem;
import net.mcreator.endgamereborn.item.NetheriteAxeRebornItem;
import net.mcreator.endgamereborn.item.NetheriteArmorRebornItem;
import net.mcreator.endgamereborn.item.GildedSteelSwordItem;
import net.mcreator.endgamereborn.item.GildedSteelShovelItem;
import net.mcreator.endgamereborn.item.GildedSteelPickaxeItem;
import net.mcreator.endgamereborn.item.GildedSteelIngotItem;
import net.mcreator.endgamereborn.item.GildedSteelHoeItem;
import net.mcreator.endgamereborn.item.GildedSteelAxeItem;
import net.mcreator.endgamereborn.item.GildedSteelArmorItem;
import net.mcreator.endgamereborn.item.FracturedSteelSwordItem;
import net.mcreator.endgamereborn.item.FracturedSteelShovelItem;
import net.mcreator.endgamereborn.item.FracturedSteelIngotItem;
import net.mcreator.endgamereborn.item.FracturedSteelHoeItem;
import net.mcreator.endgamereborn.item.FracturedSteelAxeItem;
import net.mcreator.endgamereborn.item.FracturedSteelArmorItem;
import net.mcreator.endgamereborn.item.ForgottenSteelSwordItem;
import net.mcreator.endgamereborn.item.ForgottenSteelShovelItem;
import net.mcreator.endgamereborn.item.ForgottenSteelPickaxeItem;
import net.mcreator.endgamereborn.item.ForgottenSteelIngotItem;
import net.mcreator.endgamereborn.item.ForgottenSteelHoeItem;
import net.mcreator.endgamereborn.item.ForgottenSteelAxeItem;
import net.mcreator.endgamereborn.item.ForgottenSteelArmorItem;
import net.mcreator.endgamereborn.item.DiamondArmorRebornItem;
import net.mcreator.endgamereborn.EndgameRebornMod;

public class EndgameRebornModItems {
	public static Item FORGOTTEN_STEEL_INGOT;
	public static Item GILDED_STEEL_INGOT;
	public static Item REINFORCED_STEEL_INGOT;
	public static Item REMNANT_STEEL_SCRAP;
	public static Item REMNANT_STEEL_ORE;
	public static Item GILDED_STEEL_ARMOR_HELMET;
	public static Item GILDED_STEEL_ARMOR_CHESTPLATE;
	public static Item GILDED_STEEL_ARMOR_LEGGINGS;
	public static Item GILDED_STEEL_ARMOR_BOOTS;
	public static Item GILDED_STEEL_SWORD;
	public static Item GILDED_STEEL_PICKAXE;
	public static Item GILDED_STEEL_AXE;
	public static Item GILDED_STEEL_SHOVEL;
	public static Item GILDED_STEEL_HOE;
	public static Item REINFORCED_STEEL_ARMOR_HELMET;
	public static Item REINFORCED_STEEL_ARMOR_CHESTPLATE;
	public static Item REINFORCED_STEEL_ARMOR_LEGGINGS;
	public static Item REINFORCED_STEEL_ARMOR_BOOTS;
	public static Item REINFORCED_STEEL_SWORD;
	public static Item NETHERITE_ARMOR_REBORN_HELMET;
	public static Item NETHERITE_ARMOR_REBORN_CHESTPLATE;
	public static Item NETHERITE_ARMOR_REBORN_LEGGINGS;
	public static Item NETHERITE_ARMOR_REBORN_BOOTS;
	public static Item NETHERITE_SWORD_REBORN;
	public static Item NETHERITE_PICKAXE_REBORN;
	public static Item NETHERITE_AXE_REBORN;
	public static Item NETHERITE_SHOVEL_REBORN;
	public static Item NETHERITE_HOE_REBORN;
	public static Item DIAMOND_ARMOR_REBORN_HELMET;
	public static Item DIAMOND_ARMOR_REBORN_CHESTPLATE;
	public static Item DIAMOND_ARMOR_REBORN_LEGGINGS;
	public static Item DIAMOND_ARMOR_REBORN_BOOTS;
	public static Item FORGOTTEN_STEEL_SWORD;
	public static Item FRACTURED_STEEL_INGOT;
	public static Item STEEL_INGOT;
	public static Item SCULK_STEEL_INGOT;
	public static Item REINFORCED_STEEL_PICKAXE;
	public static Item REINFORCED_STEEL_AXE;
	public static Item REINFORCED_STEEL_SHOVEL;
	public static Item REINFORCED_STEEL_HOE;
	public static Item FORGOTTEN_STEEL_ARMOR_HELMET;
	public static Item FORGOTTEN_STEEL_ARMOR_CHESTPLATE;
	public static Item FORGOTTEN_STEEL_ARMOR_LEGGINGS;
	public static Item FORGOTTEN_STEEL_ARMOR_BOOTS;
	public static Item FORGOTTEN_STEEL_PICKAXE;
	public static Item FORGOTTEN_STEEL_AXE;
	public static Item FORGOTTEN_STEEL_SHOVEL;
	public static Item FORGOTTEN_STEEL_HOE;
	public static Item STEEL_ARMOR_HELMET;
	public static Item STEEL_ARMOR_CHESTPLATE;
	public static Item STEEL_ARMOR_LEGGINGS;
	public static Item STEEL_ARMOR_BOOTS;
	public static Item STEEL_PICKAXE;
	public static Item STEEL_SWORD;
	public static Item STEEL_AXE;
	public static Item STEEL_SHOVEL;
	public static Item STEEL_HOE;
	public static Item FRACTURED_STEEL_ARMOR_HELMET;
	public static Item FRACTURED_STEEL_ARMOR_CHESTPLATE;
	public static Item FRACTURED_STEEL_ARMOR_LEGGINGS;
	public static Item FRACTURED_STEEL_ARMOR_BOOTS;
	public static Item FRACTURED_STEEL_SWORD;
	public static Item FRACTURED_STEEL_AXE;
	public static Item FRACTURED_STEEL_SHOVEL;
	public static Item FRACTURED_STEEL_HOE;
	public static Item SCULK_STEEL_ARMOR_HELMET;
	public static Item SCULK_STEEL_ARMOR_CHESTPLATE;
	public static Item SCULK_STEEL_ARMOR_LEGGINGS;
	public static Item SCULK_STEEL_ARMOR_BOOTS;
	public static Item SCULK_STEEL_SWORD;
	public static Item SCULK_STEEL_PICKAXE;
	public static Item SCULK_STEEL_AXE;
	public static Item SCULK_STEEL_SHOVEL;
	public static Item SCULK_STEEL_HOE;
	public static Item PROSPEROUS_STEEL_ARMOR_HELMET;
	public static Item PROSPEROUS_STEEL_ARMOR_CHESTPLATE;
	public static Item PROSPEROUS_STEEL_ARMOR_LEGGINGS;
	public static Item PROSPEROUS_STEEL_ARMOR_BOOTS;
	public static Item PROSPEROUS_STEEL_INGOT;
	public static Item PROSPEROUS_STEEL_SWORD;
	public static Item PROSPEROUS_STEEL_PICKAXE;
	public static Item PROSPEROUS_STEEL_AXE;
	public static Item PROSPEROUS_STEEL_SHOVEL;
	public static Item PROSPEROUS_STEEL_HOE;

	public static void load() {
		FORGOTTEN_STEEL_INGOT = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "forgotten_steel_ingot"), new ForgottenSteelIngotItem());
		GILDED_STEEL_INGOT = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "gilded_steel_ingot"), new GildedSteelIngotItem());
		REINFORCED_STEEL_INGOT = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "reinforced_steel_ingot"), new ReinforcedSteelIngotItem());
		REMNANT_STEEL_SCRAP = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "remnant_steel_scrap"), new RemnantSteelScrapItem());
		REMNANT_STEEL_ORE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "remnant_steel_ore"), new BlockItem(EndgameRebornModBlocks.REMNANT_STEEL_ORE, new Item.Properties().tab(CreativeModeTab.TAB_MATERIALS)));
		GILDED_STEEL_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "gilded_steel_armor_helmet"), new GildedSteelArmorItem.Helmet());
		GILDED_STEEL_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "gilded_steel_armor_chestplate"), new GildedSteelArmorItem.Chestplate());
		GILDED_STEEL_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "gilded_steel_armor_leggings"), new GildedSteelArmorItem.Leggings());
		GILDED_STEEL_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "gilded_steel_armor_boots"), new GildedSteelArmorItem.Boots());
		GILDED_STEEL_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "gilded_steel_sword"), new GildedSteelSwordItem());
		GILDED_STEEL_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "gilded_steel_pickaxe"), new GildedSteelPickaxeItem());
		GILDED_STEEL_AXE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "gilded_steel_axe"), new GildedSteelAxeItem());
		GILDED_STEEL_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "gilded_steel_shovel"), new GildedSteelShovelItem());
		GILDED_STEEL_HOE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "gilded_steel_hoe"), new GildedSteelHoeItem());
		REINFORCED_STEEL_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "reinforced_steel_armor_helmet"), new ReinforcedSteelArmorItem.Helmet());
		REINFORCED_STEEL_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "reinforced_steel_armor_chestplate"), new ReinforcedSteelArmorItem.Chestplate());
		REINFORCED_STEEL_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "reinforced_steel_armor_leggings"), new ReinforcedSteelArmorItem.Leggings());
		REINFORCED_STEEL_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "reinforced_steel_armor_boots"), new ReinforcedSteelArmorItem.Boots());
		REINFORCED_STEEL_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "reinforced_steel_sword"), new ReinforcedSteelSwordItem());
		NETHERITE_ARMOR_REBORN_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "netherite_armor_reborn_helmet"), new NetheriteArmorRebornItem.Helmet());
		NETHERITE_ARMOR_REBORN_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "netherite_armor_reborn_chestplate"), new NetheriteArmorRebornItem.Chestplate());
		NETHERITE_ARMOR_REBORN_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "netherite_armor_reborn_leggings"), new NetheriteArmorRebornItem.Leggings());
		NETHERITE_ARMOR_REBORN_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "netherite_armor_reborn_boots"), new NetheriteArmorRebornItem.Boots());
		NETHERITE_SWORD_REBORN = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "netherite_sword_reborn"), new NetheriteSwordItem());
		NETHERITE_PICKAXE_REBORN = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "netherite_pickaxe_reborn"), new NetheritePickaxeRebornItem());
		NETHERITE_AXE_REBORN = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "netherite_axe_reborn"), new NetheriteAxeRebornItem());
		NETHERITE_SHOVEL_REBORN = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "netherite_shovel_reborn"), new NetheriteShovelRebornItem());
		NETHERITE_HOE_REBORN = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "netherite_hoe_reborn"), new NetheriteHoeRebornItem());
		DIAMOND_ARMOR_REBORN_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "diamond_armor_reborn_helmet"), new DiamondArmorRebornItem.Helmet());
		DIAMOND_ARMOR_REBORN_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "diamond_armor_reborn_chestplate"), new DiamondArmorRebornItem.Chestplate());
		DIAMOND_ARMOR_REBORN_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "diamond_armor_reborn_leggings"), new DiamondArmorRebornItem.Leggings());
		DIAMOND_ARMOR_REBORN_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "diamond_armor_reborn_boots"), new DiamondArmorRebornItem.Boots());
		FORGOTTEN_STEEL_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "forgotten_steel_sword"), new ForgottenSteelSwordItem());
		FRACTURED_STEEL_INGOT = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "fractured_steel_ingot"), new FracturedSteelIngotItem());
		STEEL_INGOT = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "steel_ingot"), new SteelIngotItem());
		SCULK_STEEL_INGOT = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "sculk_steel_ingot"), new SculkSteelIngotItem());
		REINFORCED_STEEL_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "reinforced_steel_pickaxe"), new ReinforcedSteelPickaxeItem());
		REINFORCED_STEEL_AXE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "reinforced_steel_axe"), new ReinforcedSteelAxeItem());
		REINFORCED_STEEL_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "reinforced_steel_shovel"), new ReinforcedSteelShovelItem());
		REINFORCED_STEEL_HOE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "reinforced_steel_hoe"), new ReinforcedSteelHoeItem());
		FORGOTTEN_STEEL_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "forgotten_steel_armor_helmet"), new ForgottenSteelArmorItem.Helmet());
		FORGOTTEN_STEEL_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "forgotten_steel_armor_chestplate"), new ForgottenSteelArmorItem.Chestplate());
		FORGOTTEN_STEEL_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "forgotten_steel_armor_leggings"), new ForgottenSteelArmorItem.Leggings());
		FORGOTTEN_STEEL_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "forgotten_steel_armor_boots"), new ForgottenSteelArmorItem.Boots());
		FORGOTTEN_STEEL_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "forgotten_steel_pickaxe"), new ForgottenSteelPickaxeItem());
		FORGOTTEN_STEEL_AXE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "forgotten_steel_axe"), new ForgottenSteelAxeItem());
		FORGOTTEN_STEEL_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "forgotten_steel_shovel"), new ForgottenSteelShovelItem());
		FORGOTTEN_STEEL_HOE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "forgotten_steel_hoe"), new ForgottenSteelHoeItem());
		STEEL_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "steel_armor_helmet"), new SteelArmorItem.Helmet());
		STEEL_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "steel_armor_chestplate"), new SteelArmorItem.Chestplate());
		STEEL_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "steel_armor_leggings"), new SteelArmorItem.Leggings());
		STEEL_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "steel_armor_boots"), new SteelArmorItem.Boots());
		STEEL_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "steel_pickaxe"), new SteelPickaxeItem());
		STEEL_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "steel_sword"), new SteelSwordItem());
		STEEL_AXE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "steel_axe"), new SteelAxeItem());
		STEEL_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "steel_shovel"), new SteelShovelItem());
		STEEL_HOE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "steel_hoe"), new SteelHoeItem());
		FRACTURED_STEEL_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "fractured_steel_armor_helmet"), new FracturedSteelArmorItem.Helmet());
		FRACTURED_STEEL_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "fractured_steel_armor_chestplate"), new FracturedSteelArmorItem.Chestplate());
		FRACTURED_STEEL_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "fractured_steel_armor_leggings"), new FracturedSteelArmorItem.Leggings());
		FRACTURED_STEEL_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "fractured_steel_armor_boots"), new FracturedSteelArmorItem.Boots());
		FRACTURED_STEEL_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "fractured_steel_sword"), new FracturedSteelSwordItem());
		FRACTURED_STEEL_AXE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "fractured_steel_axe"), new FracturedSteelAxeItem());
		FRACTURED_STEEL_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "fractured_steel_shovel"), new FracturedSteelShovelItem());
		FRACTURED_STEEL_HOE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "fractured_steel_hoe"), new FracturedSteelHoeItem());
		SCULK_STEEL_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "sculk_steel_armor_helmet"), new SculkSteelArmorItem.Helmet());
		SCULK_STEEL_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "sculk_steel_armor_chestplate"), new SculkSteelArmorItem.Chestplate());
		SCULK_STEEL_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "sculk_steel_armor_leggings"), new SculkSteelArmorItem.Leggings());
		SCULK_STEEL_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "sculk_steel_armor_boots"), new SculkSteelArmorItem.Boots());
		SCULK_STEEL_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "sculk_steel_sword"), new SculkSteelSwordItem());
		SCULK_STEEL_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "sculk_steel_pickaxe"), new SculkSteelPickaxeItem());
		SCULK_STEEL_AXE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "sculk_steel_axe"), new SculkSteelAxeItem());
		SCULK_STEEL_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "sculk_steel_shovel"), new SculkSteelShovelItem());
		SCULK_STEEL_HOE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "sculk_steel_hoe"), new SculkSteelHoeItem());
		PROSPEROUS_STEEL_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "prosperous_steel_armor_helmet"), new ProsperousSteelArmorItem.Helmet());
		PROSPEROUS_STEEL_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "prosperous_steel_armor_chestplate"), new ProsperousSteelArmorItem.Chestplate());
		PROSPEROUS_STEEL_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "prosperous_steel_armor_leggings"), new ProsperousSteelArmorItem.Leggings());
		PROSPEROUS_STEEL_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "prosperous_steel_armor_boots"), new ProsperousSteelArmorItem.Boots());
		PROSPEROUS_STEEL_INGOT = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "prosperous_steel_ingot"), new ProsperousSteelIngotItem());
		PROSPEROUS_STEEL_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "prosperous_steel_sword"), new ProsperousSteelSwordItem());
		PROSPEROUS_STEEL_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "prosperous_steel_pickaxe"), new ProsperousSteelPickaxeItem());
		PROSPEROUS_STEEL_AXE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "prosperous_steel_axe"), new ProsperousSteelAxeItem());
		PROSPEROUS_STEEL_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "prosperous_steel_shovel"), new ProsperousSteelShovelItem());
		PROSPEROUS_STEEL_HOE = Registry.register(Registry.ITEM, new ResourceLocation(EndgameRebornMod.MODID, "prosperous_steel_hoe"), new ProsperousSteelHoeItem());
	}
}
